//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
public partial class Project
{

    public ProjectImport[] importField;

    public ProjectPropertyGroup[] propertyGroupField;

    public ProjectItemGroup[] itemGroupField;

    public string toolsVersionField;

    public string defaultTargetsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Import")]
    public ProjectImport[] Import
    {
        get
        {
            return this.importField;
        }
        set
        {
            this.importField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyGroup")]
    public ProjectPropertyGroup[] PropertyGroup
    {
        get
        {
            return this.propertyGroupField;
        }
        set
        {
            this.propertyGroupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemGroup")]
    public ProjectItemGroup[] ItemGroup
    {
        get
        {
            return this.itemGroupField;
        }
        set
        {
            this.itemGroupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ToolsVersion
    {
        get
        {
            return this.toolsVersionField;
        }
        set
        {
            this.toolsVersionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DefaultTargets
    {
        get
        {
            return this.defaultTargetsField;
        }
        set
        {
            this.defaultTargetsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
public partial class ProjectImport
{

    public string projectField;

    public string conditionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
public partial class ProjectPropertyGroup
{

    public string debugSymbolsField;

    public string debugTypeField;

    public string optimizeField;

    public string outputPathField;

    public string defineConstantsField;

    public string errorReportField;

    public string warningLevelField;

    public string projectTypeGuidsField;

    public string projectGuidField;

    public string outputTypeField;

    public string appDesignerFolderField;

    public string rootNamespaceField;

    public string assemblyNameField;

    public string targetFrameworkVersionField;

    public string fileAlignmentField;

    public string useMSBuildEngineField;

    public string cryEngineLauncherPathField;

    public string cryEngineProjectPathField;

    public string cryEngineCommandArgumentsField;

    public ProjectPropertyGroupConfiguration[] configurationField;

    public ProjectPropertyGroupPlatform[] platformField;

    public string conditionField;

    /// <remarks/>
    public string DebugSymbols
    {
        get
        {
            return this.debugSymbolsField;
        }
        set
        {
            this.debugSymbolsField = value;
        }
    }

    /// <remarks/>
    public string DebugType
    {
        get
        {
            return this.debugTypeField;
        }
        set
        {
            this.debugTypeField = value;
        }
    }

    /// <remarks/>
    public string Optimize
    {
        get
        {
            return this.optimizeField;
        }
        set
        {
            this.optimizeField = value;
        }
    }

    /// <remarks/>
    public string OutputPath
    {
        get
        {
            return this.outputPathField;
        }
        set
        {
            this.outputPathField = value;
        }
    }

    /// <remarks/>
    public string DefineConstants
    {
        get
        {
            return this.defineConstantsField;
        }
        set
        {
            this.defineConstantsField = value;
        }
    }

    /// <remarks/>
    public string ErrorReport
    {
        get
        {
            return this.errorReportField;
        }
        set
        {
            this.errorReportField = value;
        }
    }

    /// <remarks/>
    public string WarningLevel
    {
        get
        {
            return this.warningLevelField;
        }
        set
        {
            this.warningLevelField = value;
        }
    }

    /// <remarks/>
    public string ProjectTypeGuids
    {
        get
        {
            return this.projectTypeGuidsField;
        }
        set
        {
            this.projectTypeGuidsField = value;
        }
    }

    /// <remarks/>
    public string ProjectGuid
    {
        get
        {
            return this.projectGuidField;
        }
        set
        {
            this.projectGuidField = value;
        }
    }

    /// <remarks/>
    public string OutputType
    {
        get
        {
            return this.outputTypeField;
        }
        set
        {
            this.outputTypeField = value;
        }
    }

    /// <remarks/>
    public string AppDesignerFolder
    {
        get
        {
            return this.appDesignerFolderField;
        }
        set
        {
            this.appDesignerFolderField = value;
        }
    }

    /// <remarks/>
    public string RootNamespace
    {
        get
        {
            return this.rootNamespaceField;
        }
        set
        {
            this.rootNamespaceField = value;
        }
    }

    /// <remarks/>
    public string AssemblyName
    {
        get
        {
            return this.assemblyNameField;
        }
        set
        {
            this.assemblyNameField = value;
        }
    }

    /// <remarks/>
    public string TargetFrameworkVersion
    {
        get
        {
            return this.targetFrameworkVersionField;
        }
        set
        {
            this.targetFrameworkVersionField = value;
        }
    }

    /// <remarks/>
    public string FileAlignment
    {
        get
        {
            return this.fileAlignmentField;
        }
        set
        {
            this.fileAlignmentField = value;
        }
    }

    /// <remarks/>
    public string UseMSBuildEngine
    {
        get
        {
            return this.useMSBuildEngineField;
        }
        set
        {
            this.useMSBuildEngineField = value;
        }
    }

    /// <remarks/>
    public string CryEngineLauncherPath
    {
        get
        {
            return this.cryEngineLauncherPathField;
        }
        set
        {
            this.cryEngineLauncherPathField = value;
        }
    }

    /// <remarks/>
    public string CryEngineProjectPath
    {
        get
        {
            return this.cryEngineProjectPathField;
        }
        set
        {
            this.cryEngineProjectPathField = value;
        }
    }

    /// <remarks/>
    public string CryEngineCommandArguments
    {
        get
        {
            return this.cryEngineCommandArgumentsField;
        }
        set
        {
            this.cryEngineCommandArgumentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Configuration", IsNullable = true)]
    public ProjectPropertyGroupConfiguration[] Configuration
    {
        get
        {
            return this.configurationField;
        }
        set
        {
            this.configurationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Platform", IsNullable = true)]
    public ProjectPropertyGroupPlatform[] Platform
    {
        get
        {
            return this.platformField;
        }
        set
        {
            this.platformField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
public partial class ProjectPropertyGroupConfiguration
{

    public string conditionField;

    public string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
public partial class ProjectPropertyGroupPlatform
{

    public string conditionField;

    public string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
public partial class ProjectItemGroup
{

    public ProjectItemGroupCompile[] compileField;

    public ProjectItemGroupReference[] referenceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Compile")]
    public ProjectItemGroupCompile[] Compile
    {
        get
        {
            return this.compileField;
        }
        set
        {
            this.compileField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public ProjectItemGroupReference[] Reference
    {
        get
        {
            return this.referenceField;
        }
        set
        {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
public partial class ProjectItemGroupCompile
{

    public string includeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Include
    {
        get
        {
            return this.includeField;
        }
        set
        {
            this.includeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
public partial class ProjectItemGroupReference
{

    public string hintPathField;

    public string privateField;

    public string includeField;

    /// <remarks/>
    public string HintPath
    {
        get
        {
            return this.hintPathField;
        }
        set
        {
            this.hintPathField = value;
        }
    }

    /// <remarks/>
    public string Private
    {
        get
        {
            return this.privateField;
        }
        set
        {
            this.privateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Include
    {
        get
        {
            return this.includeField;
        }
        set
        {
            this.includeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
public partial class NewDataSet
{

    public Project[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Project")]
    public Project[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
